"""Declarative base + naming convention for every model in this package.

The explicit naming convention is what makes Alembic's autogenerated
migrations stable across SQLite (v1) and Postgres (v2) — without it,
SQLAlchemy synthesises anonymous constraint names which differ per backend
and produce noisy diffs in alembic ``revision --autogenerate`` runs.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core import clock

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def utcnow_default() -> datetime:
    """Column-default seam: naive UTC via :mod:`app.core.clock` (ADR-0001 rule 5).

    **Naive, not aware.** These columns are ``TIMESTAMP WITHOUT TIME ZONE`` on Postgres,
    and ``DateTime`` has no bind processor — so an aware value reaches the driver as
    ``timestamptz`` and the server assignment-casts it through its own ``TimeZone``
    setting. On ``TimeZone=Asia/Kolkata`` that stores IST wall-clock, reintroducing the
    exact skew this exists to remove (see :func:`app.services.auth_service.rotate_session`,
    which subtracts ``created_at`` from a Python instant).

    **Late-bound deliberately.** ``default=clock.naive_utcnow`` would capture the function
    object at class-definition time (SQLAlchemy wraps it via ``_maybe_wrap_callable``),
    leaving nothing for ``monkeypatch.setattr(clock, "naive_utcnow", ...)`` to reach — and
    since SQLite's ``func.now()`` and the app clock are indistinguishable, an unpatchable
    default has no test that can go red. Don't inline this back into a bare reference.
    """
    return clock.naive_utcnow()


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds ``created_at`` and ``updated_at`` to any model that inherits it.

    Both are written by the app clock via :func:`utcnow_default`, so the stored value is
    naive UTC on every dialect rather than whatever the *server's* clock reads. That is
    what makes ``rotate_session``'s absolute-cap subtraction correct off SQLite.

    The DB-side ``server_default`` stays as the backstop for raw ``INSERT``s that bypass
    the ORM (migrations, scripts) — and it is not optional: ``tests/test_migration_parity``
    compares DB-side defaults, so dropping it here without editing all seven migrations
    reddens the gate.

    ``updated_at`` uses SA-side ``onupdate`` because SQLite has no native ``ON UPDATE``
    clause; SQLAlchemy applies it at statement-compile time, for ORM flush and Core
    ``update()`` alike, and never emits it into DDL.
    """

    created_at: Mapped[datetime] = mapped_column(default=utcnow_default, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        default=utcnow_default, onupdate=utcnow_default, server_default=func.now()
    )
