"""Security response-headers middleware tests (PRD §Production-grade essentials).

`SecurityHeadersMiddleware` stamps clickjacking / MIME-sniff / referrer headers on every
response; HSTS rides only a hardened https deploy (`cookie_secure`). The middleware-ordering
risk lives on the error paths — the CSRF 403 (returned by the inner middleware) and the
catch-all 500 (generated by ServerErrorMiddleware, *outside* this middleware, so stamped by
the shared helper in the 500 handler). Both are asserted here, not just the 200 route.
"""

from __future__ import annotations

from collections.abc import Iterator

import pytest
from fastapi.testclient import TestClient

from app.core.config import Settings
from app.main import app

ALLOWED = "http://localhost:3000"

_STATIC = {
    "x-content-type-options": "nosniff",
    "x-frame-options": "DENY",
    "content-security-policy": "frame-ancestors 'none'",
    "referrer-policy": "strict-origin-when-cross-origin",
}


def _assert_static_headers(headers: object) -> None:
    for name, value in _STATIC.items():
        assert headers[name] == value  # type: ignore[index]


@pytest.fixture
def boom_route() -> Iterator[str]:
    """Mount a route that raises so the catch-all 500 path is exercised (cf. test_cors)."""
    path = "/api/v1/__sec_boom__"

    async def _boom() -> None:
        raise RuntimeError("forced 500 for security-header test")

    app.add_api_route(path, _boom, methods=["GET"])
    try:
        yield path
    finally:
        app.routes[:] = [r for r in app.routes if getattr(r, "path", None) != path]


def test_static_headers_on_200(client: TestClient) -> None:
    resp = client.get("/api/v1/health")
    assert resp.status_code == 200
    _assert_static_headers(resp.headers)


def test_static_headers_on_csrf_403(client: TestClient) -> None:
    """A state-changing request with a foreign Origin is rejected 403 by the inner
    CSRF middleware — the outer security-headers middleware must still stamp it."""
    resp = client.post("/api/v1/benchmarks/refresh", headers={"Origin": "http://evil.example"})
    assert resp.status_code == 403
    _assert_static_headers(resp.headers)


def test_static_headers_on_500(client: TestClient, boom_route: str) -> None:
    """The 500 is built by ServerErrorMiddleware, outside SecurityHeadersMiddleware, so
    the headers come from the shared helper in the catch-all 500 handler, not the
    middleware. raise_server_exceptions off so we inspect the browser-visible response."""
    with TestClient(app, raise_server_exceptions=False) as c:
        resp = c.get(boom_route, headers={"Origin": ALLOWED})
    assert resp.status_code == 500
    _assert_static_headers(resp.headers)


def test_no_hsts_on_local_http(client: TestClient) -> None:
    """Default deploy is local http (cookie_secure=False) — HSTS must be absent so it
    never poisons the browser's HSTS cache for localhost."""
    resp = client.get("/api/v1/health")
    assert "strict-transport-security" not in resp.headers


def test_hsts_present_when_cookie_secure(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """On a hardened https deploy (cookie_secure=True) HSTS rides every response. Patch
    the symbol in app.middleware (where apply_security_headers reads it) rather than
    mutating the cached settings singleton."""
    hardened = Settings(
        cookie_secure=True,
        jwt_secret="a-real-random-secret",
        cors_allowed_origins="http://localhost:3000",
    )
    monkeypatch.setattr("app.middleware.get_settings", lambda: hardened)
    resp = client.get("/api/v1/health")
    assert resp.status_code == 200
    assert resp.headers["strict-transport-security"] == "max-age=31536000"
