"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-23

Hand-written (not autogenerated) so the schema reads honestly and constraint /
index names match the SA NAMING_CONVENTION in :mod:`app.models.base`. The
``tests/test_migration_parity.py`` test guards against drift between this
file and the models on every pytest run.

``downgrade()`` is DESTRUCTIVE: drops every table including the seeded v1
user. Do not run against production data without a backup.

Self-referential FKs on ``accounts.parent_account_id`` and
``transactions.transfer_pair_id`` are declared inline in ``create_table`` —
works on both SQLite and Postgres because the columns are nullable and the
references resolve to the table being created.
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ----------------------------------------------------------------- users
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
    )

    # -------------------------------------------------------------- accounts
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "credit_card",
                "bank",
                "cash",
                "investment",
                name="account_type",
                native_enum=False,
                create_constraint=True,
                validate_strings=True,
            ),
            nullable=False,
        ),
        sa.Column("issuer", sa.String(length=64), nullable=True),
        sa.Column("last4", sa.String(length=4), nullable=True),
        sa.Column(
            "opening_balance_paise",
            sa.BigInteger(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "currency",
            sa.Enum(
                "INR",
                "USD",
                name="currency",
                native_enum=False,
                create_constraint=True,
                validate_strings=True,
            ),
            nullable=False,
            server_default=sa.text("'INR'"),
        ),
        sa.Column("parent_account_id", sa.Integer(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_accounts_user_id_users"),
        sa.ForeignKeyConstraint(
            ["parent_account_id"],
            ["accounts.id"],
            name="fk_accounts_parent_account_id_accounts",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_accounts"),
    )

    # ------------------------------------------------------------ categories
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("is_seeded", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_categories_user_id_users"),
        sa.PrimaryKeyConstraint("id", name="pk_categories"),
    )
    # Partial unique index: active (non-archived) names must be unique per user.
    # Inline `__table_args__`-style placement isn't reliable for the WHERE
    # clause through Alembic — explicit op.create_index is the safe path.
    op.create_index(
        "uq_categories_active_user_name",
        "categories",
        ["user_id", "name"],
        unique=True,
        sqlite_where=sa.text("archived_at IS NULL"),
        postgresql_where=sa.text("archived_at IS NULL"),
    )

    # -------------------------------------------------------- import_batches
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("source_file_hash", sa.String(length=64), nullable=False),
        sa.Column("parser_name", sa.String(length=64), nullable=False),
        sa.Column("imported_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("skipped_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "completed",
                "failed",
                name="import_status",
                native_enum=False,
                create_constraint=True,
                validate_strings=True,
            ),
            nullable=False,
            server_default=sa.text("'pending'"),
        ),
        sa.Column("error_message", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_import_batches_user_id_users"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_import_batches_account_id_accounts",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_import_batches"),
    )
    op.create_index(
        "ix_import_batches_source_file_hash",
        "import_batches",
        ["source_file_hash"],
    )

    # ---------------------------------------------------------- transactions
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "spend",
                "income",
                "transfer",
                "refund",
                name="transaction_type",
                native_enum=False,
                create_constraint=True,
                validate_strings=True,
            ),
            nullable=False,
        ),
        sa.Column("merchant_raw", sa.String(length=512), nullable=False),
        sa.Column("merchant_normalized", sa.String(length=256), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=1024), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "import",
                "manual",
                name="transaction_source",
                native_enum=False,
                create_constraint=True,
                validate_strings=True,
            ),
            nullable=False,
        ),
        sa.Column("import_batch_id", sa.Integer(), nullable=True),
        sa.Column("transfer_pair_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_transactions_user_id_users"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_transactions_account_id_accounts",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name="fk_transactions_category_id_categories",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name="fk_transactions_import_batch_id_import_batches",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_pair_id"],
            ["transactions.id"],
            name="fk_transactions_transfer_pair_id_transactions",
        ),
        sa.UniqueConstraint(
            "user_id",
            "account_id",
            "fingerprint",
            name="uq_transactions_user_account_fingerprint",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_transactions"),
    )
    op.create_index(
        "ix_transactions_user_account_date",
        "transactions",
        ["user_id", "account_id", "date"],
    )
    op.create_index(
        "ix_transactions_user_merchant_normalized",
        "transactions",
        ["user_id", "merchant_normalized"],
    )
    op.create_index(
        "ix_transactions_user_category_date",
        "transactions",
        ["user_id", "category_id", "date"],
    )

    # ------------------------------------------------------ merchant_tag_map
    op.create_table(
        "merchant_tag_map",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_normalized", sa.String(length=256), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("last_used", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_merchant_tag_map_user_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name="fk_merchant_tag_map_category_id_categories",
        ),
        sa.UniqueConstraint(
            "user_id",
            "merchant_normalized",
            "category_id",
            name="uq_merchant_tag_map_user_merchant_category",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_merchant_tag_map"),
    )
    op.create_index(
        "ix_merchant_tag_map_user_merchant",
        "merchant_tag_map",
        ["user_id", "merchant_normalized"],
    )

    # --------------------------------------------------------- seed v1 user
    # DO NOT change this UUID without updating Settings.v1_user_id default in
    # app/core/config.py — the lifespan handler in app/main.py compares both
    # and refuses to boot on mismatch.
    users_table = sa.table(
        "users",
        sa.column("id", sa.Uuid()),
        sa.column("email", sa.String()),
    )
    op.bulk_insert(
        users_table,
        [
            {
                "id": uuid.UUID("00000000-0000-0000-0000-000000000001"),
                "email": None,
            }
        ],
    )


def downgrade() -> None:
    # Reverse dependency order. Alembic drops associated indexes / constraints
    # with the table on both SQLite and Postgres.
    op.drop_table("merchant_tag_map")
    op.drop_table("transactions")
    op.drop_table("import_batches")
    op.drop_table("categories")
    op.drop_table("accounts")
    op.drop_table("users")
