"""Pydantic schemas — HTTP boundary types (per-domain submodule).

Sibling of :mod:`app.models` (SQLAlchemy ORM models). Schemas describe the
wire format; models describe the storage format. ``from_attributes=True``
bridges ORM instances to schemas without manual field copying.
"""

from app.schemas.accounts import AccountCreate, AccountRead, AccountUpdate
from app.schemas.auth import (
    AuthConfig,
    ChangePasswordRequest,
    LoginRequest,
    RegisterRequest,
    UserRead,
)
from app.schemas.backup import BackupImportSummary
from app.schemas.benchmark import BenchmarkRead, BenchmarkRefreshSummary
from app.schemas.categories import CategoryCreate, CategoryRead, CategoryUpdate
from app.schemas.dashboards import (
    NET_WORTH_EXCLUDED_TYPES,
    AccountBalanceRow,
    AvailableYearsResponse,
    CashflowByPeriodBucket,
    CashflowByPeriodResponse,
    OverviewResponse,
    PeriodTotalsResponse,
    SpendByCategoryByPeriodBucket,
    SpendByCategoryByPeriodResponse,
    SpendByCategoryResponse,
    SpendByCategoryRow,
    SpendByPeriodBucket,
    SpendByPeriodResponse,
    SpendByTagByPeriodBucket,
    SpendByTagByPeriodResponse,
    SpendByTagPeriodTotal,
    SpendByTagResponse,
    SpendByTagRow,
    SpendCategoryPeriodTotal,
    SpendCategoryRef,
    TaggingStatsResponse,
    TagRef,
    TopMerchantRow,
    TopMerchantsResponse,
)
from app.schemas.fx import FxRefreshSummary
from app.schemas.imports import (
    ImportCommit,
    ImportSummary,
    InvestmentCsvImportSummary,
    PendingImportBatch,
)
from app.schemas.investments import (
    AssetClassAllocation,
    HoldingRead,
    HoldingsResponse,
    HoldingXirr,
    InstrumentCreate,
    InstrumentRead,
    InstrumentUpdate,
    InvestmentTransactionCreate,
    InvestmentTransactionRead,
    InvestmentTransactionUpdate,
    NavRefreshSummary,
    PortfolioSummary,
    ReinvestmentCreate,
    ReinvestmentRead,
)
from app.schemas.labels import LabelCreate, LabelRead, LabelUpdate
from app.schemas.performance import PortfolioPerformance
from app.schemas.rules import (
    CategoryRuleCreate,
    CategoryRuleRead,
    LabelRuleCreate,
    LabelRuleRead,
    MerchantRuleRead,
    RulePinPatch,
    RuleWriteResult,
)
from app.schemas.transactions import (
    TransactionCandidate,
    TransactionCreate,
    TransactionRead,
    TransactionTransferCreate,
    TransactionUpdate,
    TransferRead,
)

__all__ = [
    "AccountBalanceRow",
    "AccountCreate",
    "AccountRead",
    "AccountUpdate",
    "AssetClassAllocation",
    "AuthConfig",
    "BackupImportSummary",
    "BenchmarkRead",
    "BenchmarkRefreshSummary",
    "CashflowByPeriodBucket",
    "CashflowByPeriodResponse",
    "CategoryCreate",
    "CategoryRead",
    "CategoryRuleCreate",
    "CategoryRuleRead",
    "CategoryUpdate",
    "ChangePasswordRequest",
    "FxRefreshSummary",
    "HoldingRead",
    "HoldingsResponse",
    "HoldingXirr",
    "ImportCommit",
    "ImportSummary",
    "InstrumentCreate",
    "InstrumentRead",
    "InstrumentUpdate",
    "InvestmentCsvImportSummary",
    "InvestmentTransactionCreate",
    "InvestmentTransactionRead",
    "InvestmentTransactionUpdate",
    "ReinvestmentCreate",
    "ReinvestmentRead",
    "LabelCreate",
    "LabelRead",
    "LabelRuleCreate",
    "LabelRuleRead",
    "LabelUpdate",
    "LoginRequest",
    "MerchantRuleRead",
    "NET_WORTH_EXCLUDED_TYPES",
    "NavRefreshSummary",
    "OverviewResponse",
    "PendingImportBatch",
    "PeriodTotalsResponse",
    "PortfolioPerformance",
    "PortfolioSummary",
    "RegisterRequest",
    "RulePinPatch",
    "RuleWriteResult",
    "SpendByCategoryByPeriodBucket",
    "SpendByCategoryByPeriodResponse",
    "SpendByCategoryResponse",
    "SpendByCategoryRow",
    "SpendByPeriodBucket",
    "SpendByPeriodResponse",
    "SpendByTagByPeriodBucket",
    "SpendByTagByPeriodResponse",
    "SpendByTagPeriodTotal",
    "SpendByTagResponse",
    "SpendByTagRow",
    "SpendCategoryPeriodTotal",
    "SpendCategoryRef",
    "TagRef",
    "TaggingStatsResponse",
    "TopMerchantRow",
    "TopMerchantsResponse",
    "TransactionCandidate",
    "TransactionCreate",
    "TransactionRead",
    "TransactionTransferCreate",
    "TransactionUpdate",
    "TransferRead",
    "UserRead",
]
